name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.1.2
  just_audio: ^0.9.36
  provider: ^6.1.5
  overlay_support: ^2.0.0
  intl: 0.19.0
  flutter_chat_ui: ^1.6.7
  flutter_chat_types: ^3.6.2
  uuid: ^4.1.0
  pie_chart: ^5.4.0
  fl_chart: ^1.0.0
  percent_indicator: ^4.2.5
  table_calendar: ^3.0.9
  flutter_launcher_icons: ^0.14.4
  sqflite: ^2.4.2
  path:
  http: ^1.5.0
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  firebase_auth:
  cloud_firestore:
  flutter_localization: 
  localization: 
  flutter_background_service:
  flutter_background_service_android:
  flutter_local_notifications:
  google_mobile_ads: ^6.0.0
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_aplikasi.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  share_plus: ^7.2.1
  rename: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/food.json
    - img-project/
    - img-project/healthyfoods/
    - lib/l10n/
